### ISSUE TITLE
How to test for a potential memory leaks given the example?

### ISSUE THREAD

**Issue by grazzgit** [nektro/zigquestions#13]
Underneath a simple program for generating a list that has a random number of elements of a value between 1 and 10.
The main question I have is that when I forget to free the numberlist from the heap with a "defer numberlist.deinit(); there will be a potential memory leak.

How do I test for this in zig given this program underneath?

```zig
const std = @import("std");

pub fn main() !void {
    const numElements = try getRandomNumber(1, 255);
    const stdout = std.io.getStdOut().writer();
    var numberlist = try std.ArrayList(u8).initCapacity(
        std.heap.page_allocator,
        numElements,
    );
    // If I forget to deinit, it will leak, how do I test for this?
    // defer numberlist.deinit();

    for (numElements) |_| {
        const randomValue = try getRandomNumber(1, 10);
        try numberlist.append(randomValue);
    }
    try stdout.print("number of elements: {d}\n", .{numElements});
    try stdout.print("random number list: {any}\n\n", .{numberlist.items});
}

fn getRandomNumber(min: u8, max: u8) !u8 {
    var seed: u64 = undefined;
    try std.os.getrandom(std.mem.asBytes(&seed));
    var prng = std.rand.DefaultPrng.init(seed);
    return prng.random().intRangeAtMost(u8, min, max);
}
```

**Comment by nektro** [comment]
https://zig.guide/standard-library/allocators
https://ziglang.org/documentation/master/#Choosing-an-Allocator

please reserve questions/code review for one of the wonderful [Community](https://github.com/ziglang/zig/wiki/Community)s

**Comment by nektro** [comment]
https://zig.guide/standard-library/allocators has a great example on how to use `std.heap.GeneralPurposeAllocator` which has leak detection built-in

**Comment by grazzgit** [comment]
> https://zig.guide/standard-library/allocators has a great example on how to use `std.heap.GeneralPurposeAllocator` which has leak detection built-in

Thnx for the link and advice!
