### ISSUE TITLE
Error with build.zig -  "error: no field or member function named 'addModule' in 'Build.Step.Compile'  

### ISSUE THREAD

**Issue by mooseman** [nektro/zigquestions#16]
Hi all -  

  I'm a newcomer to Zig and *love* the feel of it!  
  Anyway -  I'm trying to build a small OS but have a problem - here's the relevant part of my build.zig file -  

[code] 
```
const std = @import("std");

pub fn build(b: *std.Build) void {

    // Create an executable for the kernel
    const kernel = b.addExecutable(.{
        .name = "Zig-DOS-Kernel", 
        .root_source_file = .{ .path = "src/kernel/main.zig" },
        .target = b.host,
    });

  //  Error is in this block of code 
    kernel.addModule(.{ 
         .name = "io", 
         .path = "src/io/io.zig" });

    kernel.addPackagePath("keybd_interrupts", "src/kernel/keybd_interrupts.zig");
    kernel.addPackagePath("mouse_interrupts", "src/kernel/mouse_interrupts.zig");
    kernel.addPackagePath("system_interrupts", "src/kernel/system_interrupts.zig");
    // Add more source files as needed

    kernel.linkLibC();
    kernel.setTarget(b.standardTargetOptions(.{}));
    kernel.install();
```
[/code]

As the title says, I get the error - ""error: no field or member function named 'addModule' in 'Build.Step.Compile'   "  

If I can get this fixed, I can also fix the interrupts part as well.  
I think I had addPackage before but that didn't work.  Changed it to addModule - no luck with that either.  

I think this should be a straightforward fix.  I'm used to dealing with Makefiles - it's just a matter of getting used to the different syntax with the Zig build system.  I *do* really like the error messages though - very helpful!  
So - hoping that someone can help out here.  Many thanks in advance! 
Bye for now -  
- mooseman

**Comment by nektro** [comment]
welcome! which version of zig are you using when compiling? a lot of build system changes happened recently so the answer would differ if you were using 0.11.0 vs a recent master build.

**Comment by mooseman** [comment]
> welcome! which version of zig are you using when compiling? a lot of build system changes happened recently so the answer would differ if you were using 0.11.0 vs a recent master build.

Hi -  thanks for your reply!  

From the file I downloaded -  
zig-linux-x86_64-0.12.0-dev.2811+3cafb9655

Cheers -  
mooseman

**Comment by nektro** [comment]
you'll want

```zig
    kernel.addModule("io", .{
        .root_source_file = .{ .path = "src/io/io.zig" },
    });
```

ref: https://github.com/ziglang/zig/blob/3cafb9655/lib/std/Build.zig#L925
ref: https://github.com/ziglang/zig/blob/3cafb9655/lib/std/Build/Module.zig#L138

you'll want to make sure you have https://github.com/zigtools/zls setup in your editor since it can be essential when exploring the standard library

hope this helps :)

**Comment by mooseman** [comment]
> you'll want
> 
> ```zig
>     kernel.addModule("io", .{
>         .root_source_file = .{ .path = "src/io/io.zig" },
>     });
> ```
> 
> ref: https://github.com/ziglang/zig/blob/3cafb9655/lib/std/Build.zig#L925 ref: https://github.com/ziglang/zig/blob/3cafb9655/lib/std/Build/Module.zig#L138
> 
> you'll want to make sure you have https://github.com/zigtools/zls setup in your editor since it can be essential when exploring the standard library
> 
> hope this helps :)

Hi nektro -  thanks very much for that!  
I tried that but got this -  

  error: no field or member function named 'addModule' in 'Build.Step.Compile'
    kernel.addModule("io", .{
    ~~~~~~^~~~~~~~~~
/home/andy/zig/lib/std/Build/Step/Compile.zig:1:1: note: struct declared here
const builtin = @import("builtin");
^~~~~
referenced by:
    runBuild__anon_8728: /home/andy/zig/lib/std/Build.zig:1987:27
    main: /home/andy/zig/lib/build_runner.zig:310:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces


Arrgh!    :)   

It's a pity as I *love* Zig!  Just unfortunate that it's so young that the API is still changing a bit.    
Cheers -  thanks again!  
-  mooseman

**Comment by nektro** [comment]
my apologies, looks like instead of `kernel.addModule` you'll want `kernel.root_module.addAnonymousImport`

**Comment by mooseman** [comment]
Woohoo!  I got the fix!  Here it is -   

[code]
kernel.root_module.addImport("io", b.createModule(.{
        .root_source_file = .{ .path = "src/io/io.zig" },
    }));
[/code] 

I got this fix from here -  
https://ziggit.dev/t/what-happened-to-addmodule/2908/3  

Very useful link!  
So, this can now be marked as solved!   

Thanks again - bye for now -  
- mooseman

**Comment by mooseman** [comment]
Hi nektro - thanks for your reply!  
  Looks like .addImport did the trick for me so I'll mark this thread as closed.  
Cheers - thanks again......   :)  
- mooseman
