### ISSUE TITLE
What's "compiler_rt"?

### ISSUE THREAD

**Issue by expikr** [nektro/zigquestions#27]

**Comment by TUSF** [comment]
As far as I understand, they're basically a collection of polyfills for basic operations that are not universally available on all CPU architectures. For example, there's plenty of CPUs that don't have floating point math available natively, so compiler_rt provides software based implementations of basic arithmetic for those types, in case you compile to those targets. Integer multiplication or division is also something not available on all architectures.

**Comment by nektro** [comment]
runtime

**Comment by nektro** [comment]
the name comes inspired from LLVM but we implemented all the routines we use from scratch in Zig
https://compiler-rt.llvm.org

**Comment by nektro** [comment]
> builtins - a simple library that provides an implementation of the low-level target-specific hooks required by code generation and other runtime components. For example, when compiling for a 32-bit target, converting a double to a 64-bit unsigned integer is compiling into a runtime call to the "__fixunsdfdi" function. The builtins library provides optimized implementations of this and other low-level routines, either in target-independent C form, or as a heavily-optimized assembly.

**Comment by nektro** [comment]
GCC has a similar project by the name of libgcc https://gcc.gnu.org/onlinedocs/gccint/Libgcc.html
