### ISSUE TITLE
When is `comptime var` useful?

### ISSUE THREAD

**Issue by expikr** [nektro/zigquestions#28]
It seems to me that all it does is to allow the same identifier to be used in different sections of the same execution block for different comptime known values via procedural mutation during comptime. 

But since it can only ever use comptime-known values in its calculations, why can’t it just be done using multiple comptime-known constants at each of those points? You’d need think of multiple names, sure, but otherwise it’s functionally the same, no?

**Comment by TUSF** [comment]
You can, for example, use it in an inline loop, where it's not really practical to just use multiple constants for each loop.

```zig
comptime var i = 0;
inline while(i < 10) : (i += 1) {
    // some example code...
}
```

Zig's print implementation also uses some `comptime var` while parsing format strings at comptime, as another example.
