### ISSUE TITLE
How to make already-spawned console window use ANSI color escapes?

### ISSUE THREAD

**Issue by expikr** [nektro/zigquestions#4]
I have the following code:

```zig
pub fn main() void {
    @import("std").debug.print("\x1b[30;47m" ++ "That's all," ++ "\x1b[m" ++ " folks",.{});
}
```

It displays properly in VSCode:

![image](https://github.com/nektro/zigquestions/assets/77922942/8bb46606-3bfb-45b5-a467-8543e1324654)

but not in cmd or powershell:

![image](https://github.com/nektro/zigquestions/assets/77922942/c00a8d7b-4a37-46eb-b436-e043ad532d1c)

![image](https://github.com/nektro/zigquestions/assets/77922942/de80181c-4551-45d9-80f1-94f4cd0e0c23)

**Comment by nektro** [comment]
to illuminate on what the `|4` is doing, the same can be accomplished with https://github.com/marlersoft/zigwin32

```zig
const console = win32.system.console;
const h_out = console.GetStdHandle(console.STD_OUTPUT_HANDLE);
_ = console.SetConsoleMode(h_out, console.CONSOLE_MODE.initFlags(.{
    .ENABLE_PROCESSED_INPUT = 1, //ENABLE_PROCESSED_OUTPUT
    .ENABLE_LINE_INPUT = 1, //ENABLE_WRAP_AT_EOL_OUTPUT
    .ENABLE_ECHO_INPUT = 1, //ENABLE_VIRTUAL_TERMINAL_PROCESSING
}));
```
